version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.from-existing
    container_name: cad_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./uploads:/app/uploads
      - ./import:/app/import
    environment:
      - NEO4J_URI=bolt://cad_neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    depends_on:
      - neo4j
    command: python run.py

  neo4j:
    image: neo4j:latest
    container_name: cad_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*

volumes:
  neo4j_data: 